name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: Ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: header
      run: gcc 3_Implementation/Inc/Delay.h -c
    - name: customer file
      run: gcc 3_Implementation/src/file.c -c
    - name: project file
      run: gcc 3_Implementation/src/customer.c -o bill.exe
    - name: run
      run: ./bill.exe
       
    
    
