name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: header
      run: gcc 3_Implementation/Inc/Delay.h -c
    - name: customer file
      run: gcc 3_Implementation/src/file.c -c
    - name: main
      run: gcc 3_Implementation/src/customer.c -c
    - name: run
      run: ./customer.exe
       
    
    
